spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:todos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        hikari:
            auto-commit: false
    jpa:
        database: h2
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            properties:
                hibernate.connection.provider_disables_autocommit: true
server:
    port: 8080
logging:
    level:
        com.example.todosintegration: debug
services:
    uaa:
        url: "http://mfo.test.xm-online.com.ua"
        login: "API_CLIENT"
        password: "qwerty12345"
    entity:
        url: "http://mfo.test.xm-online.com.ua"